name: "Graphite Exporter"
version: "1.0.0"
slug: "graphite_exporter"
description: "Экспорт данных Home Assistant в Graphite"
arch:
  - amd64
  - armv7
  - aarch64
startup: "services"
ports:
  9108/tcp: 9108
